# Cleaning dataset

Objectives 📑
1. reporting null values
2. outliers detection system
3. executing defined cleaning tasks

## Execution details ⚙️

1. Reporting null values 🏮

Null or error with data reporting flow, simple iteration with all of the column and detecting which column consist of how many null values and error based values

2. Outlier detection 🔺

Numerical values : Mathematical logic to find unusual numbers
Categorical values : Odd one out of all possible elements

In [57]:
# Dirty data generation
import pandas as pd
import numpy as np

# 10x5 dataset containing edge-case anomalies
data = {
    "user_id": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "age": [np.nan, -12.0, 250.0, 22.0, 58.0, 31.0, 29.0, 36.0, 36.0, 50.0],
    "salary": [50000.0, 62000.0, 75000.0, np.nan, -999.0, 99000000.0, 60000.0, 60000.0, 68000.0, 88000.0],
    "plan_type": ["Basic", "Premium", "Basic", "Premium", "Standard", "Basic", None, "Hacker", "Basic", "Standard"],
    "device": ["Mobile", "Desktop", "Mobile", "Tablet", "Desktop", "Mobile", "Desktop", "Tablet", "NULL", "None"]
}

df_test = pd.DataFrame(data)

df_test

   user_id    age      salary plan_type   device
0      101    NaN     50000.0     Basic   Mobile
1      102  -12.0     62000.0   Premium  Desktop
2      103  250.0     75000.0     Basic   Mobile
3      104   22.0         NaN   Premium   Tablet
4      105   58.0      -999.0  Standard  Desktop
5      106   31.0  99000000.0     Basic   Mobile
6      107   29.0     60000.0       NaN  Desktop
7      108   36.0     60000.0    Hacker   Tablet
8      109   36.0     68000.0     Basic     NULL
9      110   50.0     88000.0  Standard     None

## Cleaning Unit

Foundational cleaning of wrong unputs and outliers from string and numberical entries
both consisting of vast spectrum of possibilities and options to go with a robust cleaning utility.

Pandas Data type detection api
```series.dtype``` fetch data type of the column

## Workflow

1. Pandas as primary frontline cleaning tool

Using pandas native functions and tools to apply basic filteration to the dataset
primary listing utilites
+ pd.tonumeric() : changing non-numeric mixed values to numericals
+ fillna() : Filling Null values with given quantity
+ dropna() : droping null values
+ clip() : seting range for the numeric values
+ astype() : Load types from int to float
+ abs() : negetive to absolute numbers

**String functions**
+ str.strip() removing leading and trailing white spaces
+ str.lower() / str.upper()  standardising text format for columns
+ str.extract() : regex extraction format
+ replace() : replacing operation for the given elements
+ drop_duplicates() : Identical columns droping function

2. Custom Dedicated function for final screening and checks

+ separating indexing information elements

In [67]:
# Foundational Data cleaning pipeline with pandas route

UNIQUE_THRESHOLD = 90

indexing_elem = [] # indexing elements

# Filter 1 : Indexing columns separation
for col in df_test.columns:
    elems = len(df_test[col].unique())
    total_elem = len(df_test[col])
    unique_rate = (elems/total_elem) * 100
    if unique_rate > UNIQUE_THRESHOLD:
        indexing_elem.append(col)

print("Indexing Elements",indexing_elem)

df = df_test.drop(indexing_elem, axis=1)

string_columns = [ col for col in df.columns if df[col].dtype == 'string' ]
numeric_columns = [ col for col in df.columns if df[col].dtype in 'int,float'.split(',') ]

# Foundational String columns filteration with pd tools

for col in string_columns:
    element = df[col]
    df[col] = element.str.strip()
    df[col] = element.str.lower()

'''
For numerical dtypes user would need to enter
1. Make column absolute with just integer
2. clip into a range
3. List out outliers
4. What to fill into null values
'''

print(f"String Columns : {string_columns}")
print(f"Numerical Columns : {numeric_columns}")

df

Indexing Elements ['user_id', 'salary']
String Columns : ['plan_type', 'device']
Numerical Columns : ['age']

     age plan_type   device
1  -12.0   premium  desktop
2  250.0     basic   mobile
4   58.0  standard  desktop
5   31.0     basic   mobile
7   36.0    hacker   tablet
8   36.0     basic     null
9   50.0  standard     none

In [64]:
# 1. Null values reporting execution
'''
Loading for checking null and nan values into the given dataset.
Edge cases to fight
Foundational string based checkig power
    Load up for normalizing during check with string protection
    loading up everyentry with apply function to check with null and Nan values

Working pipeline
Clean with pandas  - Run custom pipeline with string protection - get final report with string based elements
'''
import pandas as pd

NULL_REPORT = {}

# Before running custom pipeline for string protection remove the nans first
df_test_copy = df_test.copy()
df_test = df_test.dropna()

# Initial initiating sequence must required
for col in df_test:
    NULL_REPORT[col] = 0

def null_protection(entry:str):
    '''
    checks entry for null and none values
    input:entry
    returns:boolean
    '''
    null_group = ['null', 'none', 'nan']  # could have more

    normalized = entry.lower()
    if (normalized in null_group):
        return True
        
    return False

# Series level operation with null protections
def null_check(series:pd.Series):
    '''
    Total null count with string check
    input:Series
    return:int
    '''
    count = 0
    for element in series:
        check = null_protection(element)
        if check:
            count += 1
    return count

# Loading Null reporting valus for given dataset
string_columns = ['plan_type', 'device']

for col in string_columns:
    print("target", col)
    series = df_test[col]
    count = null_check(series)
    NULL_REPORT[col]+=count

print(NULL_REPORT)

target plan_type
target device
{'user_id': 0, 'age': 0, 'salary': 0, 'plan_type': 0, 'device': 2}